version: '3'

volumes:
  node-modules:

services:
  hugo:
    container_name: hugo
    image: peaceiris/hugo:latest
    ports:
      - 1313:1313
    volumes:
      - .:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
      
  node:
    image: node:latest
    working_dir: /node
    tty: true
    ports: 
    - '3000:3000'
    volumes:
      - .:/node
      - node-modules:/node/node_modules
    command: >
      bash -c "npm install &&
      npm install @google-analytics/data &&
      npm install dayjs"